version: '2'
services:
  web:
      image: nginx:1.13.3-alpine
      ports:
          - "80:80"
      volumes:
          - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - api
  api:
      image: khanhicetea/ys